- include: status_check.yml
  tags:
    - status 

- include: install.yml
  when: not consul_curr_installation.stat.exists
  tags:
    - install

- include: configure.yml
  when: not consul_curr_installation.stat.exists
  tags:
    - configure
