- include: install_check.yml
  tags:
    - status 

- include: install.yml
  when: skip_consul_install.stdout is not defined
  tags:
    - install

- include: configure.yml
  tags:
    - configure

- include: running_check.yml
  tags:
    - status 
